# Generated by Django 4.2 on 2024-11-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_image_image_url_image_image_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_prefix',
            new_name='url_prefix',
        ),
    ]
