# Generated by Django 4.2 on 2024-11-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_image_prefix_image_url_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
    ]
