# Generated by Django 4.2 on 2024-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_image_options_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url_prefix',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
    ]
